/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package com.mycompany.poo_tp2;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author guiad
 */
public class AppGUI extends javax.swing.JFrame {

	private String nomeArquivo;
	private File entrada;
	private Scanner leitor;
	private final JFileChooser fc = new JFileChooser(new File(System.getProperty("user.dir")));
	int returnVal;
	String linha;
	String[] token;
	ArrayList<Imovel> imoveis = new ArrayList<>(), resultado;
	int escolhaMenu;

	/**
	 * Creates new form AppGUI
	 */
	public AppGUI() {
		imoveis = new ArrayList<>();
		resultado = new ArrayList<>();
		entrada = null;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameMenu = new javax.swing.JFrame();
        labelTitulo1 = new javax.swing.JLabel();
        buttonExercicio1 = new javax.swing.JButton();
        buttonExercicio2 = new javax.swing.JButton();
        buttonExercicio3 = new javax.swing.JButton();
        buttonExercicio4 = new javax.swing.JButton();
        buttonExercicio5 = new javax.swing.JButton();
        buttonExercicio6 = new javax.swing.JButton();
        buttonExercicio7 = new javax.swing.JButton();
        botaoVoltarSelecaoArquivo = new javax.swing.JButton();
        botaoSairPrograma1 = new javax.swing.JButton();
        frameResultado = new javax.swing.JFrame();
        labelTitulo2 = new javax.swing.JLabel();
        botaoSalvarResultado = new javax.swing.JButton();
        botaoVoltarResultado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextPane();
        labelTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoEscolherArquivo = new javax.swing.JButton();
        botaoSairPrograma = new javax.swing.JButton();
        botaoAbrirArquivo = new javax.swing.JButton();
        labelNomeArquivo = new javax.swing.JLabel();

        frameMenu.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frameMenu.setTitle("Corretora de imoveis");
        frameMenu.setPreferredSize(new java.awt.Dimension(1055, 585));

        labelTitulo1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelTitulo1.setText("Corretora de imoveis");
        labelTitulo1.setToolTipText("");

        buttonExercicio1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio1.setText("Verificar se um proprietario se encontra na database");
        buttonExercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio1ActionPerformed(evt);
            }
        });

        buttonExercicio2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio2.setText("Procurar por imoveis de acordo com um valor maximo");
        buttonExercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio2ActionPerformed(evt);
            }
        });

        buttonExercicio3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio3.setText("Procurar por imoveis com uma quantidade minima de quartos");
        buttonExercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio3ActionPerformed(evt);
            }
        });

        buttonExercicio4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio4.setText("Procurar por um imovel de acordo com o seu tipo");
        buttonExercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio4ActionPerformed(evt);
            }
        });

        buttonExercicio5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio5.setText("Procurar por um imovel de acordo com o sua cidade");
        buttonExercicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio5ActionPerformed(evt);
            }
        });

        buttonExercicio6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio6.setText("Procurar por um imovel de acordo com o nome de seu proprietario");
        buttonExercicio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio6ActionPerformed(evt);
            }
        });

        buttonExercicio7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        buttonExercicio7.setText("Listar todos os imoveis");
        buttonExercicio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExercicio7ActionPerformed(evt);
            }
        });

        botaoVoltarSelecaoArquivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoVoltarSelecaoArquivo.setText("Voltar para a selecao de arquivos");
        botaoVoltarSelecaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarSelecaoArquivoActionPerformed(evt);
            }
        });

        botaoSairPrograma1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoSairPrograma1.setText("Sair");
        botaoSairPrograma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairPrograma1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameMenuLayout = new javax.swing.GroupLayout(frameMenu.getContentPane());
        frameMenu.getContentPane().setLayout(frameMenuLayout);
        frameMenuLayout.setHorizontalGroup(
            frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltarSelecaoArquivo)
                .addGap(18, 18, 18)
                .addComponent(botaoSairPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(frameMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameMenuLayout.createSequentialGroup()
                        .addComponent(buttonExercicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExercicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameMenuLayout.createSequentialGroup()
                        .addComponent(buttonExercicio5, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExercicio6))
                    .addComponent(buttonExercicio7, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(frameMenuLayout.createSequentialGroup()
                        .addComponent(buttonExercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonExercicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frameMenuLayout.setVerticalGroup(
            frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExercicio1)
                    .addComponent(buttonExercicio2))
                .addGap(70, 70, 70)
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExercicio3)
                    .addComponent(buttonExercicio4))
                .addGap(58, 58, 58)
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExercicio5)
                    .addComponent(buttonExercicio6))
                .addGap(70, 70, 70)
                .addComponent(buttonExercicio7)
                .addGap(43, 43, 43)
                .addGroup(frameMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltarSelecaoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSairPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        frameResultado.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameResultado.setPreferredSize(new java.awt.Dimension(1055, 585));

        labelTitulo2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelTitulo2.setText("Resultado");
        labelTitulo2.setToolTipText("");

        botaoSalvarResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoSalvarResultado.setText("Salvar resultado em um arquivo");
        botaoSalvarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarResultadoActionPerformed(evt);
            }
        });

        botaoVoltarResultado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoVoltarResultado.setText("Voltar");
        botaoVoltarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarResultadoActionPerformed(evt);
            }
        });

        textResultado.setEditable(false);
		textResultado.setFont(new java.awt.Font("Arial", 0, 14));
        jScrollPane1.setViewportView(textResultado);

        javax.swing.GroupLayout frameResultadoLayout = new javax.swing.GroupLayout(frameResultado.getContentPane());
        frameResultado.getContentPane().setLayout(frameResultadoLayout);
        frameResultadoLayout.setHorizontalGroup(
            frameResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameResultadoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoSalvarResultado)
                        .addGap(18, 18, 18)
                        .addComponent(botaoVoltarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frameResultadoLayout.createSequentialGroup()
                        .addComponent(labelTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );
        frameResultadoLayout.setVerticalGroup(
            frameResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoVoltarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSalvarResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Corretora de imoveis");

        labelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        labelTitulo.setText("Bem vindo a corretora de imoveis");
        labelTitulo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Escolha um arquivo com os imoveis para continuar:");

        botaoEscolherArquivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        botaoEscolherArquivo.setText("Escolher arquivo");
        botaoEscolherArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolherArquivoActionPerformed(evt);
            }
        });

        botaoSairPrograma.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoSairPrograma.setText("Sair");
        botaoSairPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairProgramaActionPerformed(evt);
            }
        });

        botaoAbrirArquivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botaoAbrirArquivo.setText("Abrir arquivo");
        botaoAbrirArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirArquivoActionPerformed(evt);
            }
        });

        labelNomeArquivo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAbrirArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(botaoSairPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoEscolherArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(123, 123, 123))
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoEscolherArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(labelNomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSairPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAbrirArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEscolherArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolherArquivoActionPerformed
		//fc.setCurrentDirectory();
		returnVal = fc.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			entrada = fc.getSelectedFile();
			nomeArquivo = entrada.getName();
			labelNomeArquivo.setText(nomeArquivo);
		}
    }//GEN-LAST:event_botaoEscolherArquivoActionPerformed

    private void botaoSairProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairProgramaActionPerformed
		System.exit(0);
    }//GEN-LAST:event_botaoSairProgramaActionPerformed

    private void botaoAbrirArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirArquivoActionPerformed
		if (returnVal == JFileChooser.APPROVE_OPTION && entrada != null) {
			try {
				leitor = new Scanner(entrada);

				while (leitor.hasNextLine()) {
					linha = leitor.nextLine();
					token = linha.split(";");

					switch (token[0]) {
						case "casa":
							if (token.length == 11) 
								imoveis.add(new Casa(1, Float.parseFloat(token[1]), token[2], token[3], token[4], token[5],
									Integer.parseInt(token[6]), Integer.parseInt(token[7]), Integer.parseInt(token[8]),
									Integer.parseInt(token[9]), Integer.parseInt(token[10])));
							break;
						case "apartamento":
							if (token.length == 13)
								imoveis.add(new Apartamento(2, Float.parseFloat(token[1]), token[2], token[3], token[4], token[5],
									Integer.parseInt(token[6]), Integer.parseInt(token[7]), Integer.parseInt(token[8]),
									Integer.parseInt(token[9]), Float.parseFloat(token[10]), Integer.parseInt(token[11]),
									Integer.parseInt(token[12])));
							break;
						case "chacara":
							if (token.length == 14)
								imoveis.add(new Chacara(3, Float.parseFloat(token[1]), token[2], token[3], token[4], token[5],
									Integer.parseInt(token[6]), Integer.parseInt(token[7]), Integer.parseInt(token[8]),
									Integer.parseInt(token[9]), Integer.parseInt(token[10]), Integer.parseInt(token[11]),
									Integer.parseInt(token[12]), Integer.parseInt(token[13])));
							break;
						default:
							System.out.println("Imovel desconhecido.");
							break;
					}
				}
				leitor.close();

				if (imoveis.isEmpty()) {
					labelNomeArquivo.setText("Nao foi encontrado nenhum imovel no arquivo \"" + nomeArquivo + "\"!");
					JOptionPane.showMessageDialog(rootPane, "Nao foi encontrado nenhum imovel no arquivo \"" + nomeArquivo + "\"!\nEscolha outro arquivo.\n");
				} else {
					frameMenu.setSize(1200, 600);
					frameMenu.setVisible(true);
					this.setVisible(false);
				}

				/*for (Imovel i : imoveis) {
					System.out.println(i);
				}*/
			} catch (FileNotFoundException e) {
				labelNomeArquivo.setText("Nao foi possivel abrir o arquivo com os imoveis.");
				System.out.println("Nao foi possivel abrir o arquivo com os imoveis.");
			}
		} else {
			labelNomeArquivo.setText("Nao foi escolhido nenhum arquivo.");
			System.out.println("Nao foi escolhido nenhum arquivo.");
		}
    }//GEN-LAST:event_botaoAbrirArquivoActionPerformed

    private void botaoSairPrograma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairPrograma1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairPrograma1ActionPerformed

    private void botaoVoltarSelecaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarSelecaoArquivoActionPerformed
        frameMenu.setVisible(false);
		imoveis.clear();
		resultado.clear();
		entrada = null;
		labelNomeArquivo.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_botaoVoltarSelecaoArquivoActionPerformed

    private void buttonExercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio4ActionPerformed
		String idString = JOptionPane.showInputDialog("\n(1) - Casa.\n(2) - Apartamento.\n(3) - Chacara.\nDigite o id dos imoveis que procura:");
		if (idString != null) {
			try {
				int id = Integer.parseInt(idString);
				resultado.clear();
				textResultado.setText("");
				for (Imovel i : imoveis) {
					if (i.getId() == id) {
						resultado.add(i);
						textResultado.setText(textResultado.getText() + i.toString());
					}
				}
				if (resultado.isEmpty()) {
					textResultado.setText("Nao foi encontrado nenhum imovel com este id.\n");
				}

				frameResultado.setSize(1200, 600);
				frameResultado.setVisible(true);
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(rootPane, "Entrada invalida.");
			}
		}
    }//GEN-LAST:event_buttonExercicio4ActionPerformed

    private void botaoSalvarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarResultadoActionPerformed
		FileWriter escritor;
		returnVal = fc.showOpenDialog(this);

		if (returnVal == JFileChooser.APPROVE_OPTION) {
			entrada = fc.getSelectedFile();
			try {
				escritor = new FileWriter(entrada);

				for (Imovel i : resultado) {
					escritor.write(i.toString());
				}

				escritor.close();
				JOptionPane.showMessageDialog(rootPane, "Resultado salvo no arquivo \"" + entrada.getName() + "\".\n");
			} catch (FileNotFoundException e) {
				System.out.println("Nao foi possivel abrir o arquivo para salvar os resultados.");
			} catch (IOException ex) {
				Logger.getLogger(AppGUI.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_botaoSalvarResultadoActionPerformed

    private void botaoVoltarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarResultadoActionPerformed
		frameResultado.dispose();
    }//GEN-LAST:event_botaoVoltarResultadoActionPerformed

    private void buttonExercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio1ActionPerformed
		String proprietario = JOptionPane.showInputDialog("Digite o nome do proprietario que procura:");
		if (proprietario != null) {
			boolean resul = false;
			resultado.clear();
			textResultado.setText("");
			for (Imovel i : imoveis) {
				if (proprietario.equals(i.getProprietario())) {
					resul = true;
				}
			}

			if (resul) {
				JOptionPane.showMessageDialog(rootPane, "Proprietario " + proprietario + " encontrado.");
			} else {
				JOptionPane.showMessageDialog(rootPane, "Proprietario " + proprietario + " nao encontrado.");
			}
		}
    }//GEN-LAST:event_buttonExercicio1ActionPerformed

    private void buttonExercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio2ActionPerformed
		String string = JOptionPane.showInputDialog("Digite o valor dos imoveis que procura:");
		if (string != null) {
			try {
				float valor = Float.parseFloat(string);
				resultado.clear();
				textResultado.setText("");
				for (Imovel i : imoveis) {
					if (i.getValor() <= valor) {
						resultado.add(i);
						textResultado.setText(textResultado.getText() + i.toString());
					}
				}
				if (resultado.isEmpty()) {
					textResultado.setText("Nao foi encontrado nenhum imovel abaixo de R$" + valor + ".\n");
				}

				frameResultado.setSize(1200, 600);
				frameResultado.setVisible(true);
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(rootPane, "Entrada invalida.");
			}
		}
    }//GEN-LAST:event_buttonExercicio2ActionPerformed

    private void buttonExercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio3ActionPerformed
		String string = JOptionPane.showInputDialog("Digite a quantidade de quartos dos imoveis que procura:");
		if (string != null) {
			try {
				int quartos = Integer.parseInt(string);
				resultado.clear();
				textResultado.setText("");
				for (Imovel i : imoveis) {
					if (i.getQuartos() >= quartos) {
						resultado.add(i);
						textResultado.setText(textResultado.getText() + i.toString());
					}
				}
				if (resultado.isEmpty()) {
					textResultado.setText("Nao foi encontrado nenhum imovel com mais do que " + quartos + " quartos.\n");
				}

				frameResultado.setSize(1200, 600);
				frameResultado.setVisible(true);
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(rootPane, "Entrada invalida.");
			}
		}
    }//GEN-LAST:event_buttonExercicio3ActionPerformed

    private void buttonExercicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio5ActionPerformed
		String string = JOptionPane.showInputDialog("Digite a cidade dos imoveis que procura:");
		if (string != null) {
			resultado.clear();
			textResultado.setText("");
			for (Imovel i : imoveis) {
				if (string.equals(i.getCidade())) {
					resultado.add(i);
				}
			}

			if (resultado.isEmpty()) {
				textResultado.setText("Nao foi encontrado nenhum imovel na cidade " + string + ".\n");
			} else {
				resultado.sort(Comparator.comparing(Imovel::getValor));
				for (Imovel i : resultado) {
					textResultado.setText(textResultado.getText() + i.toString());
				}		
			}	

			frameResultado.setSize(1200, 600);
			frameResultado.setVisible(true);
		}
    }//GEN-LAST:event_buttonExercicio5ActionPerformed

    private void buttonExercicio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio6ActionPerformed
		String string = JOptionPane.showInputDialog("Digite o nome do proprietario que procura:");
		if (string != null) {
			resultado.clear();
			textResultado.setText("");
			for (Imovel i : imoveis) {
				if (string.equals(i.getProprietario())) {
					resultado.add(i);
				}
			}

			if (resultado.isEmpty()) {
				textResultado.setText("Nao foi encontrado nenhum imovel que pertence a " + string + ".\n");
			} else {
				resultado.sort((im1, im2) -> Math.round(im2.getValor() - im1.getValor()));
				for (Imovel i : resultado) {
					textResultado.setText(textResultado.getText() + i.toString());
				}
			}

			frameResultado.setSize(1200, 600);
			frameResultado.setVisible(true);
		}
    }//GEN-LAST:event_buttonExercicio6ActionPerformed

    private void buttonExercicio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExercicio7ActionPerformed
		resultado.clear();
		textResultado.setText("");

		if (imoveis.isEmpty()) {
			textResultado.setText("Nao foi encontrado nenhum imovel no arquivo \"" + nomeArquivo + "\".\n");
		} else {
			for (Imovel i : imoveis) {
				resultado.add(i);
				textResultado.setText(textResultado.getText() + i.toString());
			}
		}

		frameResultado.setSize(1200, 600);
		frameResultado.setVisible(true);
    }//GEN-LAST:event_buttonExercicio7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AppGUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAbrirArquivo;
    private javax.swing.JButton botaoEscolherArquivo;
    private javax.swing.JButton botaoSairPrograma;
    private javax.swing.JButton botaoSairPrograma1;
    private javax.swing.JButton botaoSalvarResultado;
    private javax.swing.JButton botaoVoltarResultado;
    private javax.swing.JButton botaoVoltarSelecaoArquivo;
    private javax.swing.JButton buttonExercicio1;
    private javax.swing.JButton buttonExercicio2;
    private javax.swing.JButton buttonExercicio3;
    private javax.swing.JButton buttonExercicio4;
    private javax.swing.JButton buttonExercicio5;
    private javax.swing.JButton buttonExercicio6;
    private javax.swing.JButton buttonExercicio7;
    private javax.swing.JFrame frameMenu;
    private javax.swing.JFrame frameResultado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNomeArquivo;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTitulo1;
    private javax.swing.JLabel labelTitulo2;
    private javax.swing.JTextPane textResultado;
    // End of variables declaration//GEN-END:variables
}
